[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'heavenshell/vim-tslint'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'quramy/tsuquyomi'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'zxqfl/tabnine-vim'

[[plugins]]
repo = 'hashivim/vim-terraform'
