version: 2
root-markers:
  - .git/
tools:
  prettier: &prettier
    format-command: 'npx --no-install prettier --stdin-filepath ${INPUT}'
    format-stdin: true
languages:
  typescript:
    - <<: *prettier
  typescriptreact:
    - <<: *prettier
